#ifndef INCLUDED_SROOK_MATH_CONSTANTS_ALGORITHM_POW_HPP
#define INCLUDED_SROOK_MATH_CONSTANTS_ALGORITHM_POW_HPP

#include <srook/math/config/builtin.hpp>

#if SROOK_USE_BUILT_IN_CMATH_FUNCTION
#endif
