language: cpp
script:
        - g++-7 --version
        - cd tests && make
        - make clean
compiler:
        - gcc-7
before_install:
    - sudo apt remove -qq -y postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.6 postgresql-contrib-9.6
    - sudo apt -qq -y update 
    - sudo apt -qq upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
    - sudo apt -qq dist-upgrade -y
install:
    - sudo apt -qq -y install build-essential software-properties-common
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt -qq update -y
    - sudo apt -qq install gcc-7 g++-7 -y
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - sudo update-alternatives --config gcc
    - sudo apt -qq -y install cppcheck
    - wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
    - tar xzf boost_1_64_0.tar.gz
    - mv boost_1_64_0/boost .
