env:
  global:
    - secure: apzb29h6d8RuJ2deS+VFtbIpoHjqEZo5mXIW4fcLel0eCNtzJNqvuPadCPJkyyyfBfX9ZZp7BNwwrKx/LA8x1KI6PD4CLbaoYONe7JJIAoBiCYqroK+DRf92ZmydVj+dJoJchuwBIvyUU+tFo2wQHCt+dBHrhjHnIediS/3LmA7V8KehAiRwVxkdcLS3dWohEZhIwt2z+utKoyWsdF/MU64ltVUpzpi3YfPIuGmGPHwsPBjemIEg5NH3UWcveulBUGILkfoDvxvqdvTTs21zchZflnk/70VDSRF4EQI4RPGgQi+MMLNx25Odftm1J/THTHz08pKCKWdXlJNWyJEveIZ4UrD3TSsuHyhVGCNrGzIETspVa+yvo8RfPLR2FbeK4N/YxoZaKNX27vrI61bPAperz02SYRTdOCxDaH1owWAXGWbpxptF9Sqrj1xLK1zuIJql+MtQzPPfLCJAtciEctpVeim11FZhDzRjJkwAthnHW8XYzgD0qc592rvf7jneiWci2N+XWURrY+aBoSOlapBTDOINt1WtXjwgfNM5OuJSpHahnIN4ZKixaeS9YBXjJ4GO3u1ZRl1H8NBX0ETIqHNNuOEUvtnmHKhQQHs4G2BlK3NDswE+d6LQ5S/l6pEmHRsq1OGaj+Qb6HiYgLyDHmAapROP3A/bkpyxXLHLBrw=

notifications:
  slack:
    secure: ujjO4WTtnEa5yq5HuEy+dcqjmEOTuoYyaRIBnt7dgf+8tv+nv4NsvGNURaYH2QTXjMOnVTTUUmPb3YnMgAQCXQlVQTsfqq1kHXgBNZPVYvazN9NB+3sseGBv5kwur+BWP3gLPgtfU0kuNSLFC+g2BoGjZ6dZZQ+jq4UtYCp/9NhZlbQVRj7HiKLTbTHS4UPh/ZxAZqT4hSN75NlY4P+7+9QkyOjcL7bQy8jlpTDE6Y0FJtQk6ibWqoigmMGoPZv9JVvpL4SPZV/3v8cwzXiYfhBJkOqpYjnC62pGF4kzemn3yTaIJFQoN5xiXQiCkg4IWylNt1G4DTd5zYmj/zLqPfH2nuABJBw27hZxYUxJwxDJUojz84phnOq5iv+7MmbkPXhQSo+mM81a2sUfQWcncU5bFV+ZM5ZhXCUZdpjbQRiCzD6+/bFBHxkRCpPy0WIDFaEhixXeAzAYrafNZJ10EIqKVfdO9AZCwSmzV/q84AK1ZZkyHfOHdhafoBCZ9+nQbOkesoNPiBN6aqqBatgFExT8qs445TCDoIKV2xF36V9hw26sRv3nqRclDGfDkmlEPJm0PdNT8e5lxpASgY2DcC7AdT2GqcWvhbq9zPh4y8okBnR4Xc+r1gBYbYgL6htiIISdv1L8pNiayZIR49OXiKFd8SILRCPcye/2Lz+UCkc=

apt:
    update: true

language: cpp
os:
    - linux
sudo: required
dist: trusty
script:
    - g++-7 --version
    - cd tests && make && make run
    - make clean
    - make -f Makefile.zlib run
    - make -f Makefile.zlib clean
    - chmod +x ./cstring/sde_script.sh
    - ./cstring/sde_script.sh 1
    - ./cstring/sde_script.sh 0
    - make -f ./cstring/Makefile && make -f ./cstring/Makefile run && make -f ./cstring/Makefile clean
compiler:
    - gcc
before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./travis/linux/before_install.sh; ./travis/linux/before_install.sh; fi;
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x ./travis/mac/before_install.sh; ./travis/mac/before_install.sh; fi;
install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./travis/linux/install.sh; ./travis/linux/install.sh; fi;
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod +x ./travis/osx/install.sh; ./travis/osx/install.sh; fi;
    - wget -q -O boost_1_65_1.tar.gz http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
    - tar xzf boost_1_65_1.tar.gz
    - cd boost_1_65_1
    - ./bootstrap.sh
    - ./b2 link=static,shared install -d0 -j3 --prefix=../ --with-program_options
    - export LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH
    - cd ../
