notifications:
  email: false

language: cpp
os:
    - linux
dist: trusty
jobs:
  include:
  - stage: Run container build
    os: linux
    services: docker
    script: 
    - cd tests
    - SDE_URL="$(echo $SDE_URL | base64 -d)" docker-compose run test
