// Copyright (C) 2011-2019 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_EXCEPTION_HIDDEN_HPP
#define INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_EXCEPTION_HIDDEN_HPP

#ifndef SROOK_ATTRIBUTE_EXCEPTION_ABI_HIDDEN
#	define SROOK_ATTRIBUTE_EXCEPTION_ABI_HIDDEN
#endif

#endif
