// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_CONSTANT_SEQUENCE_ALGORITHM_HPP
#define INCLUDED_SROOK_CONSTANT_SEQUENCE_ALGORITHM_HPP
#include<type_traits>
#include<utility>
#include<srook/mpl/constant_sequence/algorithm/adjacent_find.hpp>
#include<srook/mpl/constant_sequence/algorithm/all_of.hpp>
#include<srook/mpl/constant_sequence/algorithm/any_of.hpp>
#include<srook/mpl/constant_sequence/algorithm/at.hpp>
#include<srook/mpl/constant_sequence/algorithm/binary_search.hpp>
#include<srook/mpl/constant_sequence/algorithm/bound.hpp>
#include<srook/mpl/constant_sequence/algorithm/concat.hpp>
#include<srook/mpl/constant_sequence/algorithm/count.hpp>
#include<srook/mpl/constant_sequence/algorithm/count_if.hpp>
#include<srook/mpl/constant_sequence/algorithm/equal.hpp>
#include<srook/mpl/constant_sequence/algorithm/equal_range.hpp>
#include<srook/mpl/constant_sequence/algorithm/erase.hpp>
#include<srook/mpl/constant_sequence/algorithm/erase_all.hpp>
#include<srook/mpl/constant_sequence/algorithm/erase_if.hpp>
#include<srook/mpl/constant_sequence/algorithm/erase_index.hpp>
#include<srook/mpl/constant_sequence/algorithm/erase_n.hpp>
#include<srook/mpl/constant_sequence/algorithm/erase_duplicate.hpp>
#include<srook/mpl/constant_sequence/algorithm/filter.hpp>
#include<srook/mpl/constant_sequence/algorithm/find.hpp>
#include<srook/mpl/constant_sequence/algorithm/find_end.hpp>
#include<srook/mpl/constant_sequence/algorithm/find_if.hpp>
#include<srook/mpl/constant_sequence/algorithm/find_if_not.hpp>
#include<srook/mpl/constant_sequence/algorithm/find_index.hpp>
#include<srook/mpl/constant_sequence/algorithm/find_if_index.hpp>
#include<srook/mpl/constant_sequence/algorithm/first.hpp>
#include<srook/mpl/constant_sequence/algorithm/for_each.hpp>
#include<srook/mpl/constant_sequence/algorithm/includes.hpp>
#include<srook/mpl/constant_sequence/algorithm/insert.hpp>
#include<srook/mpl/constant_sequence/algorithm/inplace_merge.hpp>
#include<srook/mpl/constant_sequence/algorithm/is_all_comp.hpp>
#include<srook/mpl/constant_sequence/algorithm/is_heap.hpp>
#include<srook/mpl/constant_sequence/algorithm/is_partitioned.hpp>
#include<srook/mpl/constant_sequence/algorithm/is_permutation.hpp>
#include<srook/mpl/constant_sequence/algorithm/is_sorted.hpp>
#include<srook/mpl/constant_sequence/algorithm/is_sorted_until.hpp>
#include<srook/mpl/constant_sequence/algorithm/iter_swap.hpp>
#include<srook/mpl/constant_sequence/algorithm/last.hpp>
#include<srook/mpl/constant_sequence/algorithm/length.hpp>
#include<srook/mpl/constant_sequence/algorithm/nth_element.hpp>
#include<srook/mpl/constant_sequence/algorithm/nth_max.hpp>
#include<srook/mpl/constant_sequence/algorithm/nth_min.hpp>
#include<srook/mpl/constant_sequence/algorithm/none_of.hpp>
#include<srook/mpl/constant_sequence/algorithm/make_heap.hpp>
#include<srook/mpl/constant_sequence/algorithm/merge.hpp>
#include<srook/mpl/constant_sequence/algorithm/minmax.hpp>
#include<srook/mpl/constant_sequence/algorithm/mismatch.hpp>
#include<srook/mpl/constant_sequence/algorithm/partial_head.hpp>
#include<srook/mpl/constant_sequence/algorithm/partial_tail.hpp>
#include<srook/mpl/constant_sequence/algorithm/prev_rotate.hpp>
#include<srook/mpl/constant_sequence/algorithm/pop_back.hpp>
#include<srook/mpl/constant_sequence/algorithm/pop_front.hpp>
#include<srook/mpl/constant_sequence/algorithm/replace.hpp>
#include<srook/mpl/constant_sequence/algorithm/replace_all.hpp>
#include<srook/mpl/constant_sequence/algorithm/reverse.hpp>
#include<srook/mpl/constant_sequence/algorithm/rotate.hpp>
#include<srook/mpl/constant_sequence/algorithm/search.hpp>
#include<srook/mpl/constant_sequence/algorithm/search_n.hpp>
#include<srook/mpl/constant_sequence/algorithm/set_difference.hpp>
#include<srook/mpl/constant_sequence/algorithm/set_intersection.hpp>
#include<srook/mpl/constant_sequence/algorithm/size.hpp>
#include<srook/mpl/constant_sequence/algorithm/sort.hpp>
#include<srook/mpl/constant_sequence/algorithm/summation.hpp>
#include<srook/mpl/constant_sequence/algorithm/swap.hpp>
#include<srook/mpl/constant_sequence/algorithm/swap_at.hpp>
#include<srook/mpl/constant_sequence/algorithm/transfer.hpp>
#include<srook/mpl/constant_sequence/algorithm/transfer_array.hpp>
#endif
