#
# Copyright (C) 2011-2019 Roki. Distributed under the MIT License.
#

GXX := g++-7
INCLUDE_DIR := -I../ -isystem ../include
FLAGS := -Wall -Wextra -pedantic -std=c++1z
LIBS := -L../lib -lboost_program_options -lz -pthread
TARGET1 := ./algorithm/coding/zlib/zlib_test.cpp
TARGET2 := ./algorithm/coding/zlib/blob_decompress.cpp

all: test

test: $(TARGET1) $(TARGET2)
	$(GXX) $(INCLUDE_DIR) $(TARGET1) $(LIBS) $(FLAGS) -o zlib1.o
	$(GXX) $(INCLUDE_DIR) $(TARGET2) $(LIBS) $(FLAGS) -o zlib2.o

run: test
	./zlib1.o -h
	chmod +x ../travis/script/get_sample_txt.sh
	 ../travis/script/get_sample_txt.sh 
	head -n 15 45-0.txt
	./zlib1.o -c 6 -i 45-0.txt
	file 45-0.txt_out
	wc 45-0.txt 45-0.txt_out
	./zlib1.o -d -i 45-0.txt_out
	diff -q 45-0.txt 45-0.txt_out_out	
	gzip 45-0.txt
	./zlib1.o -d -i 45-0.txt.gz
	diff -q 45-0.txt.gz_out  45-0.txt_out_out
	git clone https://github.com/falgon/git_playground.git
	./zlib2.o git_playground/.git/objects/ce/013625030ba8dba906f756967f9e9ca394464a # say hello
clean:
	$(RM) -r git_playground zlib1.o zlib2.o 45-0.txt 45-0.txt_out 45-0.txt_out_out 45-0.txt.gz 45-0.txt.gz_out
