// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_TYPE_TRAITS_HPP
#define INCLUDED_SROOK_TYPE_TRAITS_HPP
#include <srook/type_traits/add_const.hpp>
#include <srook/type_traits/add_cv.hpp>
#include <srook/type_traits/add_pointer.hpp>
#include <srook/type_traits/add_rvalue_reference.hpp>
#include <srook/type_traits/add_volatile.hpp>
#include <srook/type_traits/aligned_storage.hpp>
#include <srook/type_traits/aligned_union.hpp>
#include <srook/type_traits/any_constant.hpp>
#include <srook/type_traits/bool_constant.hpp>
#include <srook/type_traits/concepts.hpp>
#include <srook/type_traits/conditional.hpp>
#include <srook/type_traits/conjunction.hpp>
#include <srook/type_traits/copy_move_able.hpp>
#include <srook/type_traits/decay.hpp>
#include <srook/type_traits/detail.hpp>
#include <srook/type_traits/disable_if.hpp>
#include <srook/type_traits/disjunction.hpp>
#include <srook/type_traits/enable_disable_if.hpp>
#include <srook/type_traits/enable_if.hpp>
#include <srook/type_traits/extent.hpp>
#include <srook/type_traits/float_promote.hpp>
#include <srook/type_traits/has_iterator.hpp>
#include <srook/type_traits/integral_constant.hpp>
#include <srook/type_traits/invoke_result.hpp>
#include <srook/type_traits/is_arithmetic.hpp>
#include <srook/type_traits/is_array.hpp>
#include <srook/type_traits/is_assignable.hpp>
#include <srook/type_traits/is_base_of.hpp>
#include <srook/type_traits/is_callable.hpp>
#include <srook/type_traits/is_character.hpp>
#include <srook/type_traits/is_class.hpp>
#include <srook/type_traits/is_constexpr_function.hpp>
#include <srook/type_traits/is_constructible.hpp>
#include <srook/type_traits/is_convertible.hpp>
#include <srook/type_traits/is_copy_assignable.hpp>
#include <srook/type_traits/is_copy_constructible.hpp>
#include <srook/type_traits/is_copyable.hpp>
#include <srook/type_traits/is_default_constructible.hpp>
#include <srook/type_traits/is_destructible.hpp>
#include <srook/type_traits/is_enum.hpp>
#include <srook/type_traits/is_equal.hpp>
#include <srook/type_traits/is_final.hpp>
#include <srook/type_traits/is_floating_point.hpp>
#include <srook/type_traits/is_function.hpp>
#include <srook/type_traits/is_integral.hpp>
#include <srook/type_traits/is_invocable.hpp>
#include <srook/type_traits/is_lvalue_reference.hpp>
#include <srook/type_traits/is_member_function_pointer.hpp>
#include <srook/type_traits/is_member_object_pointer.hpp>
#include <srook/type_traits/is_member_pointer.hpp>
#include <srook/type_traits/is_movable.hpp>
#include <srook/type_traits/is_move_assignable.hpp>
#include <srook/type_traits/is_move_constructible.hpp>
#include <srook/type_traits/is_nothrow_assignable.hpp>
#include <srook/type_traits/is_nothrow_constructible.hpp>
#include <srook/type_traits/is_nothrow_default_constructible.hpp>
#include <srook/type_traits/is_nothrow_destructible.hpp>
#include <srook/type_traits/is_nothrow_invocable.hpp>
#include <srook/type_traits/is_nothrow_invocable_r.hpp>
#include <srook/type_traits/is_nothrow_move_constructible.hpp>
#include <srook/type_traits/is_nullptr.hpp>
#include <srook/type_traits/is_object.hpp>
#include <srook/type_traits/is_pointer.hpp>
#include <srook/type_traits/is_reference.hpp>
#include <srook/type_traits/is_referenceable.hpp>
#include <srook/type_traits/is_rvalue_reference.hpp>
#include <srook/type_traits/is_same.hpp>
#include <srook/type_traits/is_same_all.hpp>
#include <srook/type_traits/is_scalar.hpp>
#include <srook/type_traits/is_static_castable.hpp>
#include <srook/type_traits/is_swappable.hpp>
#include <srook/type_traits/is_tuple.hpp>
#include <srook/type_traits/is_union.hpp>
#include <srook/type_traits/is_void.hpp>
#include <srook/type_traits/library_concepts.hpp>
#include <srook/type_traits/negation.hpp>
#include <srook/type_traits/remove_all_extents.hpp>
#include <srook/type_traits/remove_all_reference.hpp>
#include <srook/type_traits/remove_const.hpp>
#include <srook/type_traits/remove_cv.hpp>
#include <srook/type_traits/remove_extent.hpp>
#include <srook/type_traits/remove_pointer.hpp>
#include <srook/type_traits/remove_reference.hpp>
#include <srook/type_traits/remove_volatile.hpp>
#include <srook/type_traits/result_of.hpp>
#include <srook/type_traits/strong_variadic_check.hpp>
#include <srook/type_traits/true_false_type.hpp>
#include <srook/type_traits/type_constant.hpp>
#endif
