// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_CONFIG_CONFIG_ENVIRONMENT_OS_WIN_CORE_HPP
#define INCLUDED_SROOK_CONFIG_CONFIG_ENVIRONMENT_OS_WIN_CORE_HPP

#ifdef _WIN32
#	define SROOK_OS_IS_WIN32 1
#	define SROOK_OBJECT_FORMAT_IS_COFF 1
#else
#	define SROOK_OS_IS_WIN32 0
#	define SROOK_OBJECT_FORMAT_IS_COFF 0
#endif

#endif
