// Copyright (C) 2011-2019 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_MATH_CONFIG_BUILTIN_HPP
#define INCLUDED_SROOK_MATH_CONFIG_BUILTIN_HPP

#include<srook/config/user_config.hpp>

#ifndef SROOK_CONFIG_DISABLE_BUILTIN_CMATH_FUNCTION
#	define SROOK_USE_BUILTIN_CMATH_FUNCTION 1
#else
#	define SROOK_USE_BUILTIN_CMATH_FUNCTION 0
#endif

#ifdef __clang__
#	define SROOK_BUILTIN_CMATH_FUNCTION_IS_DEFINED_CONSTEXPR 0
#elif defined(__GNUC__)
#	define SROOK_BUILTIN_CMATH_FUNCTION_IS_DEFINED_CONSTEXPR 1
#else
#	define SROOK_BUILTIN_CMATH_FUNCTION_IS_DEFINED_CONSTEXPR 0
#endif

#endif
