// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_CONFIG_ENV_OS_FILESYSTEM_HPP
#define INCLUDED_SROOK_CONFIG_ENV_OS_FILESYSTEM_HPP

#ifndef __CloudABI__
#	define SROOK_HAS_GLOBAL_FILESYSTEM_NAMESPACE 1
#else
#	define SROOK_HAS_GLOBAL_FILESYSTEM_NAMESPACE 0
#endif

#endif
