// Copyright (C) 2011-2020 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_ENUM_VIS_HIDDEN_HPP
#define INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_ENUM_VIS_HIDDEN_HPP

#include <srook/config/user_config.hpp> 

#ifndef SROOK_ATTRIBUTE_ENUM_VIS_HIDDEN
#	if !defined(SROOK_CONFIG_DISABLE_VISIBILITY_ANNOTATIONS) && !defined(SROOK_ATTRIBUTE_ENUM_VIS_HIDDEN)
#		define SROOK_ATTRIBUTE_ENUM_VIS_HIDDEN
#	endif
#endif

#endif
