// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_CONFIG_Z_ARCHITECTURE_CORE_HPP
#define INCLUDED_SROOK_CONFIG_Z_ARCHITECTURE_CORE_HPP
#if defined(__SYSC_ZARCH__)
#	define SROOK_ARCH_IS_ZARCH 1
#else
#	define SROOK_ARCH_IS_ZARCH 0
#endif
#endif
