// Copyright (C) 2011-2019 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_BASE_HPP
#define INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_BASE_HPP

#include <srook/config/environment/os.hpp>
#include <srook/config/user_config.hpp>

#if SROOK_OBJECT_FORMAT_IS_COFF 
#	if SROOK_CONFIG_DISABLE_VISIBILITY_ANNOTATIONS 
#		define SROOK_DLL_VIS
#		define SROOK_EXTERN_TEMPLATE_TYPE_VIS
#		define SROOK_CLASS_TEMPLATE_INSTANTIATION_VIS
#		define SROOK_OVERRIDABLE_FUNC_VIS
#	elif defined(SROOK_BUILDING_LIBRARY)
#		define SROOK_DLL_VIS __declspec(dllexport)
#		define SROOK_EXTERN_TEMPLATE_TYPE_VIS
#		define SROOK_CLASS_TEMPLATE_INSTANTIATION_VIS SROOK_DLL_VIS
#		define SROOK_OVERRIDABLE_FUNC_VIS SROOK_DLL_VIS
#	else
#		define SROOK_DLL_VIS __declspec(dllexport)
#		define SROOK_EXTERN_TEMPLATE_TYPE_VIS SROOK_DLL_VIS
#		define SROOK_CLASS_TEMPLATE_INSTANTIATION_VIS
#		define SROOK_OVERRIDABLE_FUNC_VIS
#	endif

#	define SROOK_ATTRIBUTE_TYPE_VIS_DEFAULT SROOK_DLL_VIS
#	define SROOK_ATTRIBUTE_FUNCTION_VIS_DEFAULT SROOK_DLL_VIS
#	define SROOK_ATTRIBUTE_EXTERN_VIS_DEFAULT SROOK_DLL_VIS
#	define SROOK_ATTRIBUTE_EXCEPTION_ABI_DEFAULT SROOK_DLL_VIS
#	define SROOK_ATTRIBUTE_EXCEPTION_ABI_HIDDEN

#	define SROOK_ATTRIBUTE_TEMPLATE_VIS_DEFAULT
#	define SROOK_ATTRIBUTE_TEMPLATE_VIS_HIDDEN
#	define SROOK_ATTRIBUTE_METHOD_TEMPLATE_IMPLICIT_INSTANTIATION_VIS_DEFAULT
#	define SROOK_ATTRIBUTE_METHOD_TEMPLATE_IMPLICIT_INSTANTIATION_VIS_HIDDEN
#	define SROOK_ATTRIBUTE_ENUM_VIS_DEFAULT
#	define SROOK_ATTRIBUTE_ENUM_VIS_HIDDEN

#	define SROOK_ATTRIBUTE_TYPE_VIS_HIDDEN
#	define SROOK_ATTRIBUTE_FUNCTION_VIS_HIDDEN

#include <srook/config/attribute/force_inline.hpp>
#define SROOK_INLINE_VISIBILITY SROOK_FORCE_INLINE
#define SROOK_EXTERN_TEMPLATE_INLINE_VISIBILITY SROOK_FORCE_INLINE

#else

#include <srook/config/attribute/visibility/details.hpp>
#include <srook/config/attribute/force_inline.hpp>
#define SROOK_INLINE_VISIBILITY SROOK_FORCE_INLINE
#define SROOK_EXTERN_TEMPLATE_INLINE_VISIBILITY SROOK_FORCE_INLINE

#endif
#endif
