// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_PREPROCESSOR_IF_HPP
#define INCLUDED_SROOK_PREPROCESSOR_IF_HPP

#include <srook/preprocessor/bool.hpp>
#include <srook/preprocessor/concat.hpp>

#define SROOK_PP_IF(Exp) SROOK_PP_IF_INTERNAL(SROOK_PP_BOOL(Exp))
#define SROOK_PP_IF_ELSE(Exp) SROOK_PP_IF_ELSE_INTERNAL(SROOK_PP_BOOL(Exp))

#define SROOK_PP_IF_INTERNAL(Exp) SROOK_PP_CONCAT(SROOK_PP_IF_INTERNAL_, Exp)
#define SROOK_PP_IF_INTERNAL_0(...)
#define SROOK_PP_IF_INTERNAL_1(...) __VA_ARGS__

#define SROOK_PP_IF_ELSE_INTERNAL(Exp) SROOK_PP_CONCAT(SROOK_PP_IF_ELSE_INTERNAL_, Exp)
#define SROOK_PP_IF_ELSE_INTERNAL_0(...) SROOK_PP_IF_ELSE_INTERNAL_ELSE_0
#define SROOK_PP_IF_ELSE_INTERNAL_1(...) __VA_ARGS__ SROOK_PP_IF_ELSE_INTERNAL_ELSE_1
#define SROOK_PP_IF_ELSE_INTERNAL_ELSE_0(...) __VA_ARGS__
#define SROOK_PP_IF_ELSE_INTERNAL_ELSE_1(...)

#endif
