// Copyright (C) 2011-2020 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_ENVIRONMENT_OS_APPLE_FEATURES_HPP
#define INCLUDED_SROOK_CONFIG_ENVIRONMENT_OS_APPLE_FEATURES_HPP

#include <srook/config/environment/os/apple/core.hpp>

#ifdef __clang__
#	ifdef _LIBCPP_AVAILABILITY_BAD_ARRAY_LENGTH
#		define SROOK_APPLE_BAD_ARRAY_LENGTH _LIBCPP_AVAILABILITY_BAD_ARRAY_LENGTH
#	endif
#	ifdef _LIBCPP_AVAILABILITY_BAD_ANY_CAST
#		define SROOK_APPLE_BAD_ANY_CAST _LIBCPP_AVAILABILITY_BAD_ANY_CAST
#	endif
#	ifdef _LIBCPP_AVAILABILITY_UNCAUGHT_EXCEPTIONS
#		define SROOK_APPLE_AVALAIBILITY_UNCAUGHT_EXCEPTIONS _LIBCPP_AVAILABILITY_UNCAUGHT_EXCEPTIONS
#	endif
#	ifdef _LIBCPP_AVAILABILITY_SIZED_NEW_DELETE
#		define SROOK_APPLE_AVALAIBILITY_SIZED_NEW_DELETE _LIBCPP_AVAILABILITY_SIZED_NEW_DELETE
#	endif
#	ifdef _LIBCPP_AVAILABILITY_FUTURE_ERROR
#		define SROOK_APPLE_AVALAIBILITY_FUTURE_ERROR _LIBCPP_AVAILABILITY_FUTURE_ERROR
#	endif
#	ifdef _LIBCPP_AVAILABILITY_TYPEINFO_VTABLE
#		define SROOK_APPLE_AVALAIBILITY_TYPEINFO_VTABLE _LIBCPP_AVAILABILITY_TYPEINFO_VTABLE
#	endif
#	ifdef _LIBCPP_AVAILABILITY_LOCALE_CATEGORY
#		define SROOK_APPLE_AVALAIBILITY_LOCALE_CATEGORY _LIBCPP_AVAILABILITY_LOCALE_CATEGORY
#	endif
#	ifdef _LIBCPP_AVAILABILITY_ATOMIC_SHARED_PTR
#		define SROOK_APPLE_AVALAIBILITY_ATOMIC_SHARED_PTR _LIBCPP_AVAILABILITY_ATOMIC_SHARED_PTR
#	endif
#elif defined(SROOK_APPLE)
#	define SROOK_APPLE_BAD_ARRAY_LENGTH __attribute__((unavailable))
#	define SROOK_APPLE_BAD_ANY_CAST SROOK_APPLE_BAD_ARRAY_LENGTH
#	define SROOK_APPLE_AVALAIBILITY_UNCAUGHT_EXCEPTIONS\
	__attribute__((availability(macosx, strict, introduced=10.12)))\
	__attribute__((availability(ios, strict, introduced=10.0)))\
	__attribute__((availability(tvos, strict, introduced=10.0)))\
	__attribute__((availability(watchos, strict, introduced=3.0)))
#	define SROOK_APPLE_AVALAIBILITY_SIZED_NEW_DELETE\
	SROOK_APPLE_AVALAIBILITY_UNCAUGHT_EXCEPTIONS
#	define SROOK_APPLE_AVALAIBILITY_FUTURE_ERROR\
	__attribute__((availability(macosx, strict, introduced=6.0)))
#	define SROOK_APPLE_AVALAIBILITY_TYPEINFO_VTABLE\
	__attribute__((availability(macosx, strict, introduced=10.9)))\
	__attribute__((availability(ios, strict, introduced=7.0)))
#	define SROOK_APPLE_AVALAIBILITY_LOCALE_CATEGORY\
	__attribute__((availability(macosx, strict, introduced=10.9)))\
	__attribute__((availability(ios, strict, introduced=7.0)))
#	define SROOK_APPLE_AVALAIBILITY_ATOMIC_SHARED_PTR SROOK_APPLE_AVALAIBILITY_LOCALE_CATEGORY
#endif

#ifndef SROOK_APPLE_BAD_ARRAY_LENGTH
#	define SROOK_APPLE_BAD_ARRAY_LENGTH
#endif
#ifndef SROOK_APPLE_BAD_ANY_CAST
#	define SROOK_APPLE_BAD_ANY_CAST
#endif
#ifndef SROOK_APPLE_AVALAIBILITY_UNCAUGHT_EXCEPTIONS
#	define SROOK_APPLE_AVALAIBILITY_UNCAUGHT_EXCEPTIONS
#endif
#ifndef SROOK_APPLE_AVALAIBILITY_SIZED_NEW_DELETE
#	define SROOK_APPLE_AVALAIBILITY_SIZED_NEW_DELETE
#endif
#ifndef SROOK_APPLE_AVALAIBILITY_FUTURE_ERROR
#	define SROOK_APPLE_AVALAIBILITY_FUTURE_ERROR
#endif
#ifndef SROOK_APPLE_AVALAIBILITY_TYPEINFO_VTABLE
#	define SROOK_APPLE_AVALAIBILITY_TYPEINFO_VTABLE
#endif
#ifndef SROOK_APPLE_AVALAIBILITY_LOCALE_CATEGORY
#	define SROOK_APPLE_AVALAIBILITY_LOCALE_CATEGORY
#endif
#ifndef SROOK_APPLE_AVALAIBILITY_ATOMIC_SHARED_PTR
#	define SROOK_APPLE_AVALAIBILITY_ATOMIC_SHARED_PTR
#endif
#endif
