// Copyright (C) 2011-2018 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_TMPL_VT_HPP
#define INCLUDED_SROOK_TMPL_VT_HPP

#include <srook/tmpl/vt/apply.hpp>
#include <srook/tmpl/vt/at.hpp>
#include <srook/tmpl/vt/bind.hpp>
#include <srook/tmpl/vt/compare.hpp>
#include <srook/tmpl/vt/concat.hpp>
#include <srook/tmpl/vt/cons.hpp>
#include <srook/tmpl/vt/drop.hpp>
#include <srook/tmpl/vt/drop_while.hpp>
#include <srook/tmpl/vt/drop_whileD.hpp>
#include <srook/tmpl/vt/erase.hpp>
#include <srook/tmpl/vt/erase_all.hpp>
#include <srook/tmpl/vt/erase_at.hpp>
#include <srook/tmpl/vt/erase_if.hpp>
#include <srook/tmpl/vt/erase_packer.hpp>
#include <srook/tmpl/vt/filter.hpp>
#include <srook/tmpl/vt/filterD.hpp>
#include <srook/tmpl/vt/first.hpp>
#include <srook/tmpl/vt/foldl.hpp>
#include <srook/tmpl/vt/foldr.hpp>
#include <srook/tmpl/vt/group.hpp>
#include <srook/tmpl/vt/group_by.hpp>
#include <srook/tmpl/vt/head.hpp>
#include <srook/tmpl/vt/index_of.hpp>
#include <srook/tmpl/vt/init.hpp>
#include <srook/tmpl/vt/insert_at.hpp>
#include <srook/tmpl/vt/intercalate.hpp>
#include <srook/tmpl/vt/intersperse.hpp>
#include <srook/tmpl/vt/is_contained_in.hpp>
#include <srook/tmpl/vt/is_contained_in_like.hpp>
#include <srook/tmpl/vt/last.hpp>
#include <srook/tmpl/vt/lat.hpp>
#include <srook/tmpl/vt/map.hpp>
#include <srook/tmpl/vt/max.hpp>
#include <srook/tmpl/vt/min.hpp>
#include <srook/tmpl/vt/move_at.hpp>
#include <srook/tmpl/vt/move_head.hpp>
#include <srook/tmpl/vt/move_tail.hpp>
#include <srook/tmpl/vt/not_fn.hpp>
#include <srook/tmpl/vt/null.hpp>
#include <srook/tmpl/vt/partial_head.hpp>
#include <srook/tmpl/vt/partial_tail.hpp>
#include <srook/tmpl/vt/pop_back.hpp>
#include <srook/tmpl/vt/pop_front.hpp>
#include <srook/tmpl/vt/replace.hpp>
#include <srook/tmpl/vt/replace_all.hpp>
#include <srook/tmpl/vt/replace_all_like.hpp>
#include <srook/tmpl/vt/reverse.hpp>
#include <srook/tmpl/vt/select.hpp>
#include <srook/tmpl/vt/set_difference.hpp>
#include <srook/tmpl/vt/set_product.hpp>
#include <srook/tmpl/vt/set_union.hpp>
#include <srook/tmpl/vt/size.hpp>
#include <srook/tmpl/vt/size_compare.hpp>
#include <srook/tmpl/vt/sort.hpp>
#include <srook/tmpl/vt/swap_at.hpp>
#include <srook/tmpl/vt/swap_at_specified.hpp>
#include <srook/tmpl/vt/tail.hpp>
#include <srook/tmpl/vt/take.hpp>
#include <srook/tmpl/vt/take_while.hpp>
#include <srook/tmpl/vt/take_whileD.hpp>
#include <srook/tmpl/vt/transfer.hpp>
#include <srook/tmpl/vt/transpose.hpp>
#include <srook/tmpl/vt/tt_proxy.hpp>
#include <srook/tmpl/vt/unique.hpp>

#endif
