// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_CONFIG_ARCH_SUPERH_VERSION_HPP
#define INCLUDED_SROOK_CONFIG_ARCH_SUPERH_VERSION_HPP

#if defined(SROOK_ARCH_IS_SUPERH)
#	if SROOK_ARCH_SH5
#		define SROOK_ARCH_SUPERH_VERSION 5.0.0
#	elif SROOK_ARCH_SH4
#		define SROOK_ARCH_SUPERH_VERSION 4.0.0
#	elif SROOK_ARCH_SH3
#		define SROOK_ARCH_SUPERH_VERSION 3.0.0
#	elif SROOK_ARCH_SH2
#		define SROOK_ARCH_SUPERH_VERSION 2.0.0
#	elif SROOK_ARCH_SH1
#		define SROOK_ARCH_SUPERH_VERSION 1.0.0
#	else
#		define SROOK_ARCH_SUPERH_VERSION 0
#	endif
#else
#	define SROOK_ARCH_SUPERH_VERSION 0
#endif

#endif
