// Copyright (C) 2011-2019 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_COMPILER_GCC_CORE_HPP
#define INCLUDED_SROOK_CONFIG_COMPILER_GCC_CORE_HPP
#ifdef __GNUC__

#include <srook/config/cpp_predefined.hpp>

#if SROOK_CPLUSPLUS >= SROOK_CPLUSPLUS11_CONSTANT
#   define SROOK_FUNC_NAME __func__
#else
#   define SROOK_FUNC_NAME __FUNCTION__
#endif
#define SROOK_PRETTY_FUNCTION __PRETTY_FUNCTION__
#if defined(__SIZEOF_FLOAT80__) || !defined(__STRICT_ANSI__)
#   define SROOK_HAS_FLOAT80
#endif
#if !defined(__STRICT_ANSI__) && defined(_GLIBCXX_USE_DECIMAL_FLOAT)
#   define SROOK_HAS_DECIMAL_FLOATS
#endif
#if SROOK_HAS_INCLUDE(<boost/config/compiler/gcc.hpp>)
#include <boost/config/compiler/gcc.hpp>
#define SROOK_HAS_INCLUDE_BOOST_CONFIG_COMPILER_GCC 1
#ifndef SROOK_GCC_VERSION
#   define SROOK_GCC_VERSION BOOST_GCC_VERSION
#endif
#ifdef BOOST_GCC
#   define SROOK_GCC BOOST_GCC
#endif
#ifdef BOOST_GCC_CXX11
#   define SROOK_GCC_CXX11 BOOST_GCC_CXX11
#endif
#ifdef BOOST_NO_TWO_PHASE_NAME_LOOKUP
#   define SROOK_NO_TWO_PHASE_NAME_LOOKUP BOOST_NO_TWO_PHASE_NAME_LOOKUP
#endif
#ifdef BOOST_NO_IS_ABSTRACT
#   define SROOK_NO_IS_ABSTRACT BOOST_NO_IS_ABSTRACT
#endif
#ifdef BOOST_NO_IS_ABSTRACT
#   define SROOK_NO_IS_ABSTRACT BOOST_NO_IS_ABSTRACT
#endif
#ifdef BOOST_NO_CXX11_EXTERN_TEMPLATE
#   define SROOK_NO_CXX11_EXTERN_TEMPLATE BOOST_NO_CXX11_EXTERN_TEMPLATE
#endif
#ifdef BOOST_HAS_PRAGMA_ONCE
#   define SROOK_HAS_PRAGMA_ONCE BOOST_HAS_PRAGMA_ONCE
#endif
#ifdef BOOST_NO_EXCEPTIONS
#   define SROOK_NO_EXCEPTIONS BOOST_NO_EXCEPTIONS
#endif
#if defined(BOOST_HAS_THREADS) && !defined(SROOK_HAS_THREADS)
#   define SROOK_HAS_THREADS BOOST_HAS_THREADS
#endif
#if defined(BOOST_HAS_LONG_LONG) && !defined(SROOK_HAS_LONG_LONG)
#   define SROOK_HAS_LONG_LONG BOOST_HAS_LONG_LONG
#endif
#ifdef BOOST_HAS_NRVO
#   define SROOK_HAS_NRVO BOOST_HAS_NRVO
#endif
#if GCC_VERSION <= 20096
#   ifdef __builtin_expect
#       undef __builtin_expect
#   endif
#   define __builtin_expect(x, e) (x)
#endif
#ifdef BOOST_LIKELY
#   define SROOK_LIKELY(x) BOOST_LIKELY(x)
#endif
#ifdef BOOST_UNLIKELY
#   define SROOK_UNLIKELY(x) BOOST_UNLIKELY(x)
#endif
#ifdef BOOST_HAS_DECLSPEC
#   define SROOK_HAS_DECLSPEC BOOST_HAS_DECLSPEC
#endif
#ifdef BOOST_SYMBOL_EXPORT
#   define SROOK_SYMBOL_EXPORT BOOST_SYMBOL_EXPORT
#endif
#ifdef BOOST_SYMBOL_IMPORT 
#   define SROOK_SYMBOL_IMPORT BOOST_SYMBOL_IMPORT
#endif
#ifdef BOOST_SYMBOL_VISIBLE
#   define SROOK_SYMBOL_VISIBLE BOOST_SYMBOL_VISIBLE
#endif
#ifdef BOOST_NO_TYPEID
#   define SROOK_NO_TYPEID BOOST_NO_TYPEID
#endif
#ifdef BOOST_NO_RTTI
#   define SROOK_NO_RTTI BOOST_NO_RTTI
#endif
#ifdef BOOST_NVCC_CXX11
#   define SROOK_NVCC_CXX11 BOOST_NVCC_CXX11
#endif
#ifdef BOOST_HAS_INT128
#   define SROOK_HAS_INT128 BOOST_HAS_INT128
#endif
#ifdef BOOST_HAS_FLOAT128
#   define SROOK_HAS_FLOAT128 BOOST_HAS_FLOAT128
#endif
#ifdef BOOST_HAS_DECLTYPE
#   define SROOK_HAS_DECLTYPE BOOST_HAS_DECLTYPE
#endif
#ifdef BOOST_HAS_RVALUE_REFS
#   define SROOK_HAS_RVALUE_REFS BOOST_HAS_RVALUE_REFS
#endif
#ifdef BOOST_HAS_STATIC_ASSERT
#   define SROOK_HAS_STATIC_ASSERT BOOST_HAS_STATIC_ASSERT
#endif
#ifdef BOOST_HAS_VARIADIC_TMPL
#   define SROOK_HAS_VARIADIC_TMPL BOOST_HAS_VARIADIC_TMPL
#endif
#ifdef BOOST_NO_CXX11_DECLTYPE
#   define SROOK_NO_CXX11_DECLTYPE BOOST_NO_CXX11_DECLTYPE
#endif
#ifdef BOOST_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS
#   define SROOK_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS BOOST_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS
#endif
#ifdef BOOST_NO_CXX11_RVALUE_REFERENCES
#   define SROOK_NO_CXX11_RVALUE_REFERENCES BOOST_NO_CXX11_RVALUE_REFERENCES
#endif
#ifdef BOOST_NO_CXX11_STATIC_ASSERT
#   define SROOK_NO_CXX11_STATIC_ASSERT BOOST_NO_CXX11_STATIC_ASSERT
#endif
#ifdef SROOK_NO_CXX11_AUTO_DECLARATIONS
#   define SROOK_NO_CXX11_AUTO_DECLARATIONS  BOOST_NO_CXX11_AUTO_DECLARATIONS
#endif
#ifdef BOOST_NO_CXX11_AUTO_MULTIDECLARATIONS
#   define SROOK_NO_CXX11_AUTO_MULTIDECLARATIONS BOOST_NO_CXX11_AUTO_MULTIDECLARATIONS
#endif
#ifdef BOOST_NO_CXX11_CHAR16_T
#   define SROOK_NO_CXX11_CHAR16_T BOOST_NO_CXX11_CHAR16_T
#endif
#ifdef BOOST_NO_CXX11_CHAR32_T
#   define SROOK_NO_CXX11_CHAR32_T BOOST_NO_CXX11_CHAR32_T
#endif
#ifdef BOOST_NO_CXX11_HDR_INITIALIZER_LIST
#   define SROOK_NO_CXX11_HDR_INITIALIZER_LIST BOOST_NO_CXX11_HDR_INITIALIZER_LIST
#endif
#ifdef BOOST_NO_CXX11_DEFAULTED_FUNCTIONS
#   define SROOK_NO_CXX11_DEFAULTED_FUNCTIONS BOOST_NO_CXX11_DEFAULTED_FUNCTIONS
#endif
#ifdef BOOST_NO_CXX11_DELETED_FUNCTIONS
#   define SROOK_NO_CXX11_DELETED_FUNCTIONS BOOST_NO_CXX11_DELETED_FUNCTIONS
#endif
#ifdef BOOST_NO_CXX11_TRAILING_RESULT_TYPES
#   define SROOK_NO_CXX11_TRAILING_RESULT_TYPES BOOST_NO_CXX11_TRAILING_RESULT_TYPES
#endif
#ifdef BOOST_NO_CXX11_INLINE_NAMESPACES
#   define SROOK_NO_CXX11_INLINE_NAMESPACES BOOST_NO_CXX11_INLINE_NAMESPACES
#endif
#ifdef BOOST_NO_CXX11_VARIADIC_TEMPLATES
#   define SROOK_NO_CXX11_VARIADIC_TEMPLATES BOOST_NO_CXX11_VARIADIC_TEMPLATES
#endif
#ifdef BOOST_NO_SFINAE_EXPR
#   define SROOK_NO_SFINAE_EXPR BOOST_NO_SFINAE_EXPR
#endif
#ifdef BOOST_NO_CXX11_NON_PUBLIC_DEFAULTED_FUNCTIONS
#   define SROOK_NO_CXX11_NON_PUBLIC_DEFAULTED_FUNCTIONS BOOST_NO_CXX11_NON_PUBLIC_DEFAULTED_FUNCTIONS
#endif
#ifdef BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS
#   define SROOK_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS
#endif
#ifdef BOOST_NO_CXX11_LAMBDAS
#   define SROOK_NO_CXX11_LAMBDAS BOOST_NO_CXX11_LAMBDAS
#endif
#ifdef BOOST_NO_CXX11_LOCAL_CLASS_TEMPLATE_PARAMETERS
#   define SROOK_NO_CXX11_LOCAL_CLASS_TEMPLATE_PARAMETERS BOOST_NO_CXX11_LOCAL_CLASS_TEMPLATE_PARAMETERS
#endif
#ifdef BOOST_NO_CXX11_RAW_LITERALS
#   define SROOK_NO_CXX11_RAW_LITERALS BOOST_NO_CXX11_RAW_LITERALS
#endif
#ifdef BOOST_NO_CXX11_UNICODE_LITERALS
#   define SROOK_NO_CXX11_UNICODE_LITERALS  BOOST_NO_CXX11_UNICODE_LITERALS
#endif
#ifdef BOOST_NO_CXX11_SCOPED_ENUMS
#   define SROOK_NO_CXX11_SCOPED_ENUMS  BOOST_NO_CXX11_SCOPED_ENUMS
#endif
#ifdef BOOST_NO_CXX11_CONSTEXPR
#   define SROOK_NO_CXX11_CONSTEXPR BOOST_NO_CXX11_CONSTEXPR
#endif
#ifdef BOOST_NO_CXX11_NOEXCEPT
#   define SROOK_NO_CXX11_NOEXCEPT BOOST_NO_CXX11_NOEXCEPT
#endif
#ifdef BOOST_NO_CXX11_NULLPTR
#   define SROOK_NO_CXX11_NULLPTR BOOST_NO_CXX11_NULLPTR
#endif
#ifdef BOOST_NO_CXX11_RANGE_BASED_FOR
#   define SROOK_NO_CXX11_RANGE_BASED_FOR BOOST_NO_CXX11_RANGE_BASED_FOR
#endif
#ifdef BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX
#   define SROOK_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX BOOST_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX
#endif
#ifdef BOOST_NO_CXX11_FINAL
#   define SROOK_NO_CXX11_FINAL BOOST_NO_CXX11_FINAL
#endif
#ifdef BOOST_NO_CXX11_TEMPLATE_ALIASES
#   define SROOK_NO_CXX11_TEMPLATE_ALIASES BOOST_NO_CXX11_TEMPLATE_ALIASES
#endif
#ifdef BOOST_NO_CXX11_USER_DEFINED_LITERALS
#   define SROOK_NO_CXX11_USER_DEFINED_LITERALS BOOST_NO_CXX11_USER_DEFINED_LITERALS
#endif
#ifdef BOOST_NO_CXX11_FIXED_LENGTH_VARIADIC_TEMPLATE_EXPANSION_PACKS
#   define SROOK_NO_CXX11_FIXED_LENGTH_VARIADIC_TEMPLATE_EXPANSION_PACKS BOOST_NO_CXX11_FIXED_LENGTH_VARIADIC_TEMPLATE_EXPANSION_PACKS
#endif
#ifdef BOOST_NO_CXX11_ALIGNAS
#   define SROOK_NO_CXX11_ALIGNAS BOOST_NO_CXX11_ALIGNAS
#endif
#ifdef BOOST_NO_CXX11_THREAD_LOCAL
#   define SROOK_NO_CXX11_THREAD_LOCAL BOOST_NO_CXX11_THREAD_LOCAL
#endif
#ifdef BOOST_NO_CXX11_SFINAE_EXPR
#   define SROOK_NO_CXX11_SFINAE_EXPR BOOST_NO_CXX11_SFINAE_EXPR
#endif
#ifdef BOOST_NO_CXX11_DECLTYPE_N3276
#   define SROOK_NO_CXX11_DECLTYPE_N3276  BOOST_NO_CXX11_DECLTYPE_N3276
#endif
#ifdef BOOST_NO_CXX11_REF_QUALIFIERS
#   define SROOK_NO_CXX11_REF_QUALIFIERS  BOOST_NO_CXX11_REF_QUALIFIERS
#endif
#ifdef BOOST_NO_CXX14_BINARY_LITERALS
#   define SROOK_NO_CXX14_BINARY_LITERALS BOOST_NO_CXX14_BINARY_LITERALS
#endif
#ifdef BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION
#   define SROOK_NO_CXX14_RETURN_TYPE_DEDUCTION BOOST_NO_CXX14_RETURN_TYPE_DEDUCTION
#endif
#ifdef BOOST_NO_CXX14_GENERIC_LAMBDAS
#   define SROOK_NO_CXX14_GENERIC_LAMBDAS BOOST_NO_CXX14_GENERIC_LAMBDAS
#endif
#ifdef BOOST_NO_CXX14_DIGIT_SEPARATORS
#   define SROOK_NO_CXX14_DIGIT_SEPARATORS  BOOST_NO_CXX14_DIGIT_SEPARATORS
#endif
#ifdef BOOST_NO_CXX14_DECLTYPE_AUTO
#   define SROOK_NO_CXX14_DECLTYPE_AUTO BOOST_NO_CXX14_DECLTYPE_AUTO
#endif
#ifdef BOOST_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES
#   define SROOK_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES BOOST_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES
#endif
#ifdef BOOST_NO_CXX14_AGGREGATE_NSDMI
#   define SROOK_NO_CXX14_AGGREGATE_NSDMI BOOST_NO_CXX14_AGGREGATE_NSDMI
#endif
#ifdef BOOST_NO_CXX14_CONSTEXPR
#   define SROOK_NO_CXX14_CONSTEXPR BOOST_NO_CXX14_CONSTEXPR
#endif
#ifdef BOOST_NO_CXX14_VARIABLE_TEMPLATES
#   define SROOK_NO_CXX14_VARIABLE_TEMPLATES  BOOST_NO_CXX14_VARIABLE_TEMPLATES
#endif
#ifdef SROOK_NO_CXX17_STRUCTURED_BINDINGS
#   define SROOK_NO_CXX17_STRUCTURED_BINDINGS  BOOST_NO_CXX17_STRUCTURED_BINDINGS
#endif
#ifdef BOOST_NO_CXX17_INLINE_VARIABLES
#   define SROOK_NO_CXX17_INLINE_VARIABLES BOOST_NO_CXX17_INLINE_VARIABLES
#endif
#ifdef BOOST_NO_CXX17_FOLD_EXPRESSIONS
#   define SROOK_NO_CXX17_FOLD_EXPRESSIONS BOOST_NO_CXX17_FOLD_EXPRESSIONS
#endif
#else
#ifndef SROOK_GCC_VERSION
#   define SROOK_GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#endif
#ifndef __CUDACC__
#   define SROOK_GCC SROOK_GCC_VERSION
#endif
#if defined(__GXX_EXPERIMENTAL_CXX0X__) || (SROOK_CPLUSPLUS >= SROOK_CPLUSPLUS11_CONSTANT)
#   define SROOK_GCC_CXX11
#endif
#if __GNUC__ == 3
#   ifdef __PATHSCALE__
#       define SROOK_NO_TWO_PHASE_NAME_LOOKUP
#       define SROOK_NO_IS_ABSTRACT
#   endif
#   if __GNUC_MINOR__ < 4
#       define SROOK_NO_IS_ABSTRACT
#   endif
#   define SROOK_NO_CXX11_EXTERN_TEMPLATE
#endif
#if __GNUC__ < 4
#   define SROOK_NO_TWO_PHASE_NAME_LOOKUP
#   ifdef __OPEN64__
#       define SROOK_NO_IS_ABSTRACT
#   endif
#endif
#if SROOK_GCC_VERSION >= 30400
#   define SROOK_HAS_PRAGMA_ONCE
#endif
#if SROOK_GCC_VERSION < 40400
#   define SROOK_NO_COMPLETE_VALUE_INITIALIZATION
#endif
#if !defined(__EXCEPTIONS) && !defined(SROOK_NO_EXCEPTIONS)
#   define SROOK_NO_EXCEPTIONS
#endif
#if !defined(__MINGW32__) && !defined(linux) && !defined(__linux) && !defined(__linux__) && !defined(SROOK_HAS_THREADS)
#   define SROOK_HAS_THREADS
#endif
#if !defined(__DARWIN_NO_LONG_LONG) && !defined(SROOK_HAS_LONG_LONG)
#   define SROOK_HAS_LONG_LONG
#endif
#define SROOK_HAS_NRVO
#if GCC_VERSION <= 20096
#   ifdef __builtin_expect
#       undef __builtin_expect
#   endif
#   define __builtin_expect(x, e) (x)
#endif
#define SROOK_LIKELY(x) __builtin_expect(!!(x), 1)
#define SROOK_UNLIKELY(x) __builtin_expect(!!(x), 0)

#if __GNUC__ >= 4
#   if (defined(_WIN32) || defined(__WIN32__) || defined(WIN32)) && !defined(__CYGWIN__)
#       define SROOK_HAS_DECLSPEC
#       define SROOK_SYMBOL_EXPORT __attribute__((__dllexport__))
#       define SROOK_SYMBOL_IMPORT __attribute__((__dllimport__))
#   else
#       define SROOK_SYMBOL_EXPORT __attribute__((__visibility__("default")))
#       define SROOK_SYMBOL_IMPORT
#   endif
#   define SROOK_SYMBOL_VISIBLE __attribute__((__visibility__("default")))
#else
#   define SROOK_SYMBOL_EXPORT
#endif

#if SROOK_GCC_VERSION > 40300
#   ifndef __GXX_RTTI
#       ifndef SROOK_NO_TYPEID
#           define SROOK_NO_TYPEID
#       endif
#       ifndef SROOK_NO_RTTI
#            define SROOK_NO_RTTI
#       endif
#   endif
#endif

#if defined(__CUDACC__)
#   if defined(SROOK_GCC_CXX11)
#       define SROOK_NVCC_CXX11
#   else
#       define SROOK_NVCC_CXX03
#   endif
#endif

#if defined(__SIZEOF_INT128__) && !defined(SROOK_NVCC_CXX03)
#   define SROOK_HAS_INT128
#endif

#ifdef SROOK_CPLUSPLUS
#   include <cstddef>
#else
#   include <stddef.h>
#endif
#if (defined(_GLIBCXX_USE_FLOAT128) || defined(__SIZEOF_FLOAT128__)) && !defined(__STRICT_ANSI__) && !defined(SROOK_NVCC_CXX03)
#   define SROOK_HAS_FLOAT128
#endif

#if (SROOK_GCC_VERSION >= 40300) && defined(SROOK_GCC_CXX11)
#   define SROOK_HAS_DECLTYPE
#   define SROOK_HAS_RVALUE_REFS
#   define SROOK_HAS_STATIC_ASSERT
#   define SROOK_HAS_VARIADIC_TMPL
#else
#   define SROOK_NO_CXX11_DECLTYPE
#   define SROOK_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS
#   define SROOK_NO_CXX11_RVALUE_REFERENCES
#   define SROOK_NO_CXX11_STATIC_ASSERT
#endif

#if (SROOK_GCC_VERSION < 40400) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_AUTO_DECLARATIONS
#   define SROOK_NO_CXX11_AUTO_MULTIDECLARATIONS
#   define SROOK_NO_CXX11_CHAR16_T
#   define SROOK_NO_CXX11_CHAR32_T
#   define SROOK_NO_CXX11_HDR_INITIALIZER_LIST
#   define SROOK_NO_CXX11_DEFAULTED_FUNCTIONS
#   define SROOK_NO_CXX11_DELETED_FUNCTIONS
#   define SROOK_NO_CXX11_TRAILING_RESULT_TYPES
#   define SROOK_NO_CXX11_INLINE_NAMESPACES
#   define SROOK_NO_CXX11_VARIADIC_TEMPLATES
#endif

#if SROOK_GCC_VERSION < 40500
#   define SROOK_NO_SFINAE_EXPR
#endif

#if __GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ == 5) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_NON_PUBLIC_DEFAULTED_FUNCTIONS
#endif

#if (SROOK_GCC_VERSION < 40500) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS
#   define SROOK_NO_CXX11_LAMBDAS
#   define SROOK_NO_CXX11_LOCAL_CLASS_TEMPLATE_PARAMETERS
#   define SROOK_NO_CXX11_RAW_LITERALS
#   define SROOK_NO_CXX11_UNICODE_LITERALS
#endif

#if (SROOK_GCC_VERSION < 40501) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_SCOPED_ENUMS
#endif

#if (SROOK_GCC_VERSION < 40600) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_CONSTEXPR
#   define SROOK_NO_CXX11_NOEXCEPT
#   define SROOK_NO_CXX11_NULLPTR
#   define SROOK_NO_CXX11_RANGE_BASED_FOR
#   define SROOK_NO_CXX11_UNIFIED_INITIALIZATION_SYNTAX
#endif

#if (SROOK_GCC_VERSION < 40700) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_FINAL
#   define SROOK_NO_CXX11_TEMPLATE_ALIASES
#   define SROOK_NO_CXX11_USER_DEFINED_LITERALS
#   define SROOK_NO_CXX11_FIXED_LENGTH_VARIADIC_TEMPLATE_EXPANSION_PACKS
#endif

#if (SROOK_GCC_VERSION < 40800) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_ALIGNAS
#   define SROOK_NO_CXX11_THREAD_LOCAL
#   define SROOK_NO_CXX11_SFINAE_EXPR
#endif

#if (SROOK_GCC_VERSION < 40801) || !defined(SROOK_GCC_CXX11)
#   define SROOK_NO_CXX11_DECLTYPE_N3276
#   define SROOK_NO_CXX11_REF_QUALIFIERS
#   define SROOK_NO_CXX14_BINARY_LITERALS
#endif

#if (SROOK_GCC_VERSION < 40900) || (SROOK_CPLUSPLUS < 201300)
#   define SROOK_NO_CXX14_RETURN_TYPE_DEDUCTION
#   define SROOK_NO_CXX14_GENERIC_LAMBDAS
#   define SROOK_NO_CXX14_DIGIT_SEPARATORS
#   define SROOK_NO_CXX14_DECLTYPE_AUTO
#   if !((SROOK_GCC_VERSION >= 40801) && (SROOK_GCC_VERSION < 40900) && defined(SROOK_GCC_CXX11))
#       define SROOK_NO_CXX14_INITIALIZED_LAMBDA_CAPTURES
#   endif
#endif

#if !defined(__cpp_aggregate_nsdmi) || (__cpp_aggregate_nsdmi < 201304)
#   define SROOK_NO_CXX14_AGGREGATE_NSDMI
#endif
#if !defined(__cpp_constexpr) || (__cpp_constexpr < 201304)
#   define SROOK_NO_CXX14_CONSTEXPR
#endif
#if !defined(__cpp_variable_templates) || (__cpp_variable_templates < 201304)
#   define SROOK_NO_CXX14_VARIABLE_TEMPLATES
#endif

#if !defined(__cpp_structured_bindings) || (__cpp_structured_bindings < 201606)
#   define SROOK_NO_CXX17_STRUCTURED_BINDINGS
#endif
#if !defined(__cpp_inline_variables) || (__cpp_inline_variables < 201606)
#   define SROOK_NO_CXX17_INLINE_VARIABLES
#endif
#if !defined(__cpp_fold_expressions) || (__cpp_fold_expressions < 201603)
#   define SROOK_NO_CXX17_FOLD_EXPRESSIONS
#endif

#ifndef SROOK_COMPILER
#   define SROOK_COMPILER "GNU C++ version " __VERSION__
#endif

#endif

#endif
#endif
