// Copyright (C) 2017 roki
#ifndef INCLUDED_SROOK_CONFIG_ARCH_CONVEX_VERSION_HPP
#define INCLUDED_SROOK_CONFIG_ARCH_CONVEX_VERSION_HPP
#include <srook/config/arch/Convex/core.hpp>
#if SROOK_ARCH_IS_CONVEX
#	if SROOK_CONVEX_C1
#		define SROOK_ARCH_CONVEX_VERSION 1.0
#	elif SROOK_CONVEX_C2
#		define SROOK_ARCH_CONVEX_VERSION 2.0
#	elif SROOK_CONVEX_C32
#		define SROOK_ARCH_CONVEX_VERSION 3.2
#	elif SROOK_CONVEX_C34
#		define SROOK_ARCH_CONVEX_VERSION 3.4
#	elif SROOK_CONVEX_C38
#		define SROOK_ARCH_CONVEX_VERSION 3.8
#	else
#		define SROOK_ARCH_CONVEX_VERSION 0.0
#	endif
#else
#	define SROOK_ARCH_CONVEX_VERSION 0.0
#endif

#endif
