// Copyright (C) 2011-2019 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_OVERRIDABLE_FUNCTION_DEFAULT_HPP
#define INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_OVERRIDABLE_FUNCTION_DEFAULT_HPP

#include <srook/config/attribute/visibility/detail/function/default.hpp>

#ifndef SROOK_OVERRIDABLE_FUNC_VIS_DEFAULT
#	define SROOK_OVERRIDABLE_FUNC_VIS_DEFAULT SROOK_ATTRIBUTE_FUNCTION_VIS_DEFAULT
#endif

#endif
