// Copyright (C) 2011-2018 Roki. Distributed under the MIT License
#ifndef INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_OVERRIDABLE_FUNCTION_HIDDEN_HPP
#define INCLUDED_SROOK_CONFIG_ATTRIBUTE_VISIBILITY_DETAIL_OVERRIDABLE_FUNCTION_HIDDEN_HPP

#ifndef SROOK_OVERRIDABLE_FUNC_VIS_HIDDEN
#	define SROOK_OVERRIDABLE_FUNC_VIS_HIDDEN
#endif

#endif
